stages:
  - build
  - deploy 

build app:
  stage: build 
  image: "node:12.14.0"
  artifacts:
    expire_in: 2h20min
    paths:
      - build/
  script:
    - yarn install 
    - yarn build 

deploy tsuru:
  stage: deploy
  only:
    - master 
  image: docker-hub.artifactory.globoi.com/tsuru/client:latest
  dependencies:
    - "build app"
  script:
    - cd build/ 
    - tsuru app-deploy -a cloud-toolkit .
